services:
  web:
    image: ghcr.io/fuberg/tic-tac-toe-online:latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
    expose:
      - "3000"
    networks:
      edge:
        aliases:
          - tic-tac-toe-online

networks:
  edge:
    external: true
    name: edge
