#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
REPO_SLUG="Fuberg/tic-tac-toe-online"
REPO_SLUG_LOWER=$(printf '%s' "$REPO_SLUG" | tr '[:upper:]' '[:lower:]')
KEY_PATH="$HOME/.ssh/tic-tac-toe-deploy"
REMOTE_DIR="/opt/tic-tac-toe-online"

banner "Автодеплой + домен — tic-tac-toe-online"

# ── Stage 1: dedicated deploy user + CI SSH key ────────────────────────────
stage "Сервер — пользователь для деплоя и SSH-ключ для CI"
warn "Пароль root, который вы показали в чате, теперь в истории разговора."
say "Он используется здесь только один раз, интерактивно самим SSH — этот скрипт нигде его не сохраняет."
say "После того как вход по ключу заработает (проверим ниже), смените пароль root в панели Beget или отключите парольный вход полностью (последний этап этого визарда — опционально)."
pause "Понятно, продолжаем?"

ask DEPLOY_SSH_HOST "IP или хост сервера:"
ask DEPLOY_SSH_PORT "SSH-порт (Enter = 22):"
DEPLOY_SSH_PORT="${DEPLOY_SSH_PORT:-22}"

say "Сейчас потребуется один раз ввести пароль root — сам скрипт его не читает и не хранит."
confirm "Подключиться как root к $DEPLOY_SSH_HOST:$DEPLOY_SSH_PORT и создать пользователя deploy?" || { warn "остановлено — перезапустите этап, когда будете готовы"; exit 1; }

say "Проверяю ОС и создаю пользователя deploy (с NOPASSWD sudo — это выделенный пользователь только для деплоя)..."
ssh -p "$DEPLOY_SSH_PORT" "root@$DEPLOY_SSH_HOST" '
  set -e
  cat /etc/os-release | head -3
  id -u deploy >/dev/null 2>&1 || useradd -m -s /bin/bash deploy
  mkdir -p /home/deploy/.ssh
  chown deploy:deploy /home/deploy/.ssh
  chmod 700 /home/deploy/.ssh
  printf "deploy ALL=(ALL) NOPASSWD:ALL\n" > /etc/sudoers.d/deploy
  chmod 440 /etc/sudoers.d/deploy
'

if [[ ! -f "$KEY_PATH" ]]; then
  say "Генерирую отдельный SSH-ключ для CI (не переиспользуем ваш личный)..."
  ssh-keygen -t ed25519 -f "$KEY_PATH" -N "" -C "github-actions-deploy@tic-tac-toe-online"
else
  note "используется уже существующий ключ $KEY_PATH"
fi

say "Копирую публичный ключ на сервер для пользователя deploy (снова пароль root)..."
cat "$KEY_PATH.pub" | ssh -p "$DEPLOY_SSH_PORT" "root@$DEPLOY_SSH_HOST" \
  "cat >> /home/deploy/.ssh/authorized_keys && chown deploy:deploy /home/deploy/.ssh/authorized_keys && chmod 600 /home/deploy/.ssh/authorized_keys"

say "Проверяю вход по ключу без пароля..."
if ssh -i "$KEY_PATH" -p "$DEPLOY_SSH_PORT" -o BatchMode=yes -o ConnectTimeout=5 "deploy@$DEPLOY_SSH_HOST" 'echo ok' 2>/dev/null | grep -q ok; then
  say "${GREEN}✓ вход по ключу работает${RESET}"
else
  warn "вход по ключу не подтверждён — не продолжайте, пока не разберётесь (проверьте authorized_keys на сервере)"
fi

DEPLOY_SSH_USER="deploy"
write_env DEPLOY_SSH_HOST "$DEPLOY_SSH_HOST"
write_env DEPLOY_SSH_PORT "$DEPLOY_SSH_PORT"
write_env DEPLOY_SSH_USER "$DEPLOY_SSH_USER"
set_var DEPLOY_SSH_HOST "$DEPLOY_SSH_HOST"
set_var DEPLOY_SSH_PORT "$DEPLOY_SSH_PORT"
set_var DEPLOY_SSH_USER "$DEPLOY_SSH_USER"
set_secret DEPLOY_SSH_KEY "$(cat "$KEY_PATH")"

# ── Stage 2: Docker + Compose + firewall on the server ─────────────────────
stage "Сервер — Docker, Docker Compose и firewall"
say "Устанавливаю Docker Engine + Compose plugin официальным скриптом Docker (если ещё не установлен)..."
ssh -i "$KEY_PATH" -p "$DEPLOY_SSH_PORT" "deploy@$DEPLOY_SSH_HOST" '
  set -e
  if ! command -v docker >/dev/null 2>&1; then
    curl -fsSL https://get.docker.com | sudo sh
  fi
  docker --version
  sudo docker compose version
'

say "Настраиваю firewall (ufw): разрешаю SSH-порт, 80 и 443, остальное закрыто."
confirm "Включить ufw на сервере сейчас?" && ssh -i "$KEY_PATH" -p "$DEPLOY_SSH_PORT" "deploy@$DEPLOY_SSH_HOST" "
  set -e
  sudo ufw allow $DEPLOY_SSH_PORT/tcp
  sudo ufw allow 80/tcp
  sudo ufw allow 443/tcp
  sudo ufw --force enable
  sudo ufw status
" || warn "firewall пропущен — настройте вручную при необходимости"

# ── Stage 3: production docker-compose.yml + Caddyfile on the server ───────
stage "Production docker-compose.yml + Caddyfile"
say "Caddy — обратный прокси перед приложением: сам получает TLS-сертификат (Let's Encrypt) и сам умеет проксировать WebSocket (нужно для Socket.IO) без дополнительной настройки."
ask DOMAIN "Домен, который будет указывать на приложение (например, tic-tac-toe.example.com):"
write_env DOMAIN "$DOMAIN"
set_var DOMAIN "$DOMAIN"

IMAGE="ghcr.io/$REPO_SLUG_LOWER:latest"
TMPDIR=$(mktemp -d)

cat > "$TMPDIR/docker-compose.yml" <<EOF
services:
  web:
    image: $IMAGE
    restart: unless-stopped
    environment:
      NODE_ENV: production
    expose:
      - "3000"

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  caddy_data:
  caddy_config:
EOF

cat > "$TMPDIR/Caddyfile" <<EOF
$DOMAIN {
  reverse_proxy web:3000
}
EOF

say "Копирую файлы на сервер в $REMOTE_DIR..."
ssh -i "$KEY_PATH" -p "$DEPLOY_SSH_PORT" "deploy@$DEPLOY_SSH_HOST" "sudo mkdir -p $REMOTE_DIR && sudo chown deploy:deploy $REMOTE_DIR"
scp -i "$KEY_PATH" -P "$DEPLOY_SSH_PORT" "$TMPDIR/docker-compose.yml" "$TMPDIR/Caddyfile" "deploy@$DEPLOY_SSH_HOST:$REMOTE_DIR/"
rm -rf "$TMPDIR"
say "${GREEN}✓ файлы на сервере${RESET}"
note "образ $IMAGE ещё не существует — появится после первого запуска GitHub Actions на этапе 5"

# ── Stage 4: DNS A record ───────────────────────────────────────────────────
stage "DNS — A-запись домена на IP сервера (Beget)"
say "Домен и сервер у вас в одном аккаунте Beget."
open_url "https://cp.beget.com"
step "Домены → выберите $DOMAIN → раздел управления DNS-записями."
note "Точный путь зависит от текущего интерфейса Beget — ищите пункт вида «DNS» или «Управление зоной»; я не проверял этот экран вживую, ориентируйтесь по названиям разделов."
step "Добавьте/отредактируйте A-запись: имя @ (корень домена) или нужный поддомен → значение $DEPLOY_SSH_HOST."
note "Если используете поддомен (например, play.$DOMAIN), создавайте A-запись именно для него, а не для корня."
confirm "DNS-запись создана?" || note "можно вернуться к этому этапу позже — следующие шаги можно готовить параллельно, DNS всё равно распространяется не мгновенно"
note "Распространение DNS может занять от нескольких минут до нескольких часов."

# ── Stage 5: GitHub Actions workflow ────────────────────────────────────────
stage "GitHub Actions — сборка образа и деплой по SSH"
say "Пишу .github/workflows/deploy.yml: при пуше в main собирает образ, публикует в ghcr.io (бесплатно, без доп. логина на сервере после того как сделаем пакет публичным) и деплоит на сервер по SSH."

mkdir -p .github/workflows
cat > .github/workflows/deploy.yml <<'EOF'
name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ steps.image.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Compute lowercase image name
        id: image
        run: echo "image=ghcr.io/$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.image.outputs.image }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.DEPLOY_SSH_HOST }}
          username: ${{ vars.DEPLOY_SSH_USER }}
          port: ${{ vars.DEPLOY_SSH_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /opt/tic-tac-toe-online
            sudo docker compose pull
            sudo docker compose up -d
EOF

say "${GREEN}✓ записан .github/workflows/deploy.yml${RESET}"
confirm "Закоммитить и запушить этот workflow в main прямо сейчас?" && {
  git add .github/workflows/deploy.yml
  git commit -m "Add autodeploy workflow: build image, push to GHCR, deploy over SSH"
  git push
} || note "файл не закоммичен — сделайте это вручную, когда будете готовы (git add/commit/push)"

# ── Stage 6: first deploy + make GHCR package public + verify ──────────────
stage "Первый деплой, публичность образа в GHCR, проверка"
say "Если workflow ещё не запускался — запустите его сейчас."
open_url "https://github.com/$REPO_SLUG/actions"
step "Если не запустился сам — Deploy → Run workflow → Run workflow (ветка main)."
confirm "Workflow 'Deploy' завершился успешно (зелёная галочка)?" || warn "дождитесь завершения перед следующим шагом"

say "По умолчанию GHCR создаёт новый пакет приватным — серверу нужен публичный доступ на pull без логина."
open_url "https://github.com/$REPO_SLUG/pkgs/container/tic-tac-toe-online"
step "Package settings (внизу справа) → Danger Zone → Change visibility → Public."
confirm "Пакет сделан публичным?" || warn "без этого 'docker compose pull' на сервере не сработает — вернитесь и сделайте это"

say "Проверяю сайт..."
open_url "https://$DOMAIN"
confirm "Сайт открылся по https://$DOMAIN?" && say "${GREEN}✓ автодеплой и домен работают${RESET}" || warn "проверьте по порядку: DNS-запись (этап 4), статус workflow (Actions), затем на сервере — sudo docker compose ps в $REMOTE_DIR"

# ── Stage 7 (optional): disable root/password SSH login ────────────────────
stage "(опционально) Отключить root-логин и пароль по SSH"
warn "Пароль root был показан в чате этой сессии — рекомендую сменить его или полностью отключить парольный вход."
say "Перед этим шагом убедитесь, что вход по ключу для пользователя deploy точно работает (проверено на этапе 1) — иначе рискуете потерять доступ к серверу."
if confirm "Вход по ключу точно работает, и вы хотите отключить root-логин + парольный вход по SSH?"; then
  ssh -i "$KEY_PATH" -p "$DEPLOY_SSH_PORT" "deploy@$DEPLOY_SSH_HOST" '
    set -e
    sudo sed -i "s/^#\?PermitRootLogin.*/PermitRootLogin no/" /etc/ssh/sshd_config
    sudo sed -i "s/^#\?PasswordAuthentication.*/PasswordAuthentication no/" /etc/ssh/sshd_config
    sudo systemctl reload sshd
  '
  say "${GREEN}✓ root-логин и парольный вход отключены${RESET}"
else
  note "пропущено — можно сделать позже вручную"
fi
note "Также смените сам пароль root в панели Beget, раз он был показан в чате: панель сервера → сброс/смена пароля."

finish
